// File generated by FlutterFire CLI & configured manually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA13iYz7CYp_ujAUJU5XvzRd4CItHymd_8',
    appId: '1:720777740872:web:34a0921c8df336ddef0e7d',
    messagingSenderId: '720777740872',
    projectId: 'studysync-948b3',
    authDomain: 'studysync-948b3.firebaseapp.com',
    storageBucket: 'studysync-948b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA13iYz7CYp_ujAUJU5XvzRd4CItHymd_8',
    appId: '1:720777740872:android:34a0921c8df336ddef0e7d',
    messagingSenderId: '720777740872',
    projectId: 'studysync-948b3',
    storageBucket: 'studysync-948b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA13iYz7CYp_ujAUJU5XvzRd4CItHymd_8',
    appId: '1:720777740872:ios:34a0921c8df336ddef0e7d',
    messagingSenderId: '720777740872',
    projectId: 'studysync-948b3',
    storageBucket: 'studysync-948b3.firebasestorage.app',
    iosBundleId: 'com.example.studysync',
  );
}
